### ISSUE TITLE
TODO checklist

### ISSUE THREAD

**Issue by jonathancallahan** [pnwairfire/monitoring-databrowser-v5-dev#1]
Items as they come up:

-----
_TODO:_

**mv5-simple-real-time**
- [x] PA_data_store.js and button to load synoptic data from the 'near me' service.(1/23)
- [x] Display PA data with separate callback to: 1) load data from Stuart's files; 2) plot data (1/23)

----
_Items finished by 2023-01-30_

- [x] "real-time" Not showing correct "today" data in diurnalPlot -- "today data ends at 4pm PST" regardless of current time. (1/30)

----
_Items finished by 2023-01-23_

- [x] Initial checkin of `mv5-simple-real-time` minimum viable product.
